Add New test case COC-108
TechHoldingLLC/th-hospitality-qa pull request #3
Opened 2024-12-04 12:28 UTC by Ketan-dhumal-th

2024-12-04 13:10 UTC, karishma-barot-th requested changes
Please go through added comments and make appropriate changes

2024-12-04 13:10 UTC, karishma-barot-th commented on tests/pageObjects/adminLoginPage.ts
>    async enterPassword(password: string): Promise<void> {
please use enterValuesInElement() method from base page

2024-12-04 13:10 UTC, karishma-barot-th commented on tests/pageObjects/adminLoginPage.ts
>    async clickLoginButton(): Promise<void> {
please use clickElement() method from base page

2024-12-04 13:10 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +import { expect, test, Browser, Page } from "@playwright/test";
Add appropriate comments to the file

2024-12-06 05:26 UTC, karishma-barot-th requested changes
Please work on all comments added

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/pageObjects/adminLoginPage.ts
> -  async login(email: string, password: string): Promise<void> {
keep this login() method

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +    await basePage.enterValuesInElement(loginPage.emailInput, config.email);
use here login() method from adminLoginPage.ts

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +    try {  //Click on the Users button
Comment should be explanatory for the click() event you have performed here
ex: Navigation to Users page

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +        // Enter email and click & select role, department, groups
Make your comment more meaningful. It should be something like: Fill up 'Invite User' form

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +        await basePage.clickElement(homePage.usersButton);
Add these 2 lines to before hook as you are using these lines to each test case
await basePage.clickElement(homePage.usersButton);
await basePage.clickElement(homePage.inviteUserButton);

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +        await page.waitForTimeout(3000);
avoid waits in spec file

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +        await basePage.getElementText(homePage.inviteGroupsErrorMessage);
Add assertions for all validation errors. You are only retrieving text here.

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +        await page.waitForTimeout(3000);
Avoid waits in spec file

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminHome.spec.ts
> +        const firstEmailElement = emailItems[0];
There is no need to fetch entire email list as we are not performing any action on list. Fetch the first element only and add assertion

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminLogin.spec.ts
>      await page.waitForTimeout(3000);
Avoid waits in spec file. Remove all waits from all spec files.

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminLogin.spec.ts
> +    await basePage.navigateTo(config.adminPortalUrl);
Add 'navigation to admin portal' code to before hook as you are using it to all the test cases

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminLogin.spec.ts
> +    await basePage.clickElement(loginPage.loginButton);
use login() method from adminLoginPage.ts

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminLogin.spec.ts
> +    await basePage.clickElement(loginPage.loginButton);
same, use login () method

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminLogin.spec.ts
>      await page.waitForTimeout(5000);
same, remove wait

2024-12-06 05:26 UTC, karishma-barot-th commented on tests/specs/adminLogin.spec.ts
> +    await basePage.getElementText(loginPage.errorMessage);
you need to add assertion here. You are retrieving text and doing nothing with it.

2024-12-06 13:35 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminLoginPage.ts
> -  async login(email: string, password: string): Promise<void> {
Done

2024-12-06 13:35 UTC, Ketan-dhumal-th commented on tests/specs/adminHome.spec.ts
> +import { expect, test, Browser, Page } from "@playwright/test";
Done

2024-12-06 13:36 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminHomePage.ts
> +  async clickUserButton(): Promise<void> {
Done

2024-12-06 13:37 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminHomePage.ts
> +  async clickInviteUserButton(): Promise<void> {
Done

2024-12-06 13:37 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminHomePage.ts
> +  async fillInviteUserEmail(inviteEmail: string): Promise<void> {
Done

2024-12-06 13:37 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminHomePage.ts
> +  async submitInviteButton(): Promise<void> {
Done

2024-12-06 13:37 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminHomePage.ts
> +  async getSuccessMessage(): Promise<string | null> {
Done

2024-12-06 13:37 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminLoginPage.ts
>    async navigate(url: string): Promise<void> {
Done

2024-12-09 05:32 UTC, karishma-barot-th requested changes
Added comments for minor fixes. Please address those.

2024-12-09 05:51 UTC, Ketan-dhumal-th commented on tests/pageObjects/adminLoginPage.ts
> +    this.passwardInput = page.locator("//input[@id=':r1:-form-item']");
Done

2024-12-09 07:22 UTC, Ketan-dhumal-th commented on tests/specs/adminHome.spec.ts
> +        // Click on Invite button
Done

2024-12-09 07:22 UTC, Ketan-dhumal-th commented on tests/specs/adminHome.spec.ts
> +        // Click on Users button again to view user list
Done

2024-12-09 07:22 UTC, Ketan-dhumal-th commented on tests/specs/adminLogin.spec.ts
> +    // Click the login button
Done

2024-12-09 09:25 UTC, karishma-barot-th approved these changes

2024-12-09 13:09 UTC, merged